name: Check Rust

on:
  workflow_call:
    inputs:
      rust-version:
        required: true
        type: string

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    name: Check (${{ inputs.rust-version }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: rustfmt, clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --all-targets --all-features

      - name: Run tests
        run: cargo test --all-targets --all-features
