name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, edited]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    uses: ./.github/workflows/format-rust.yml

  check-stable:
    uses: ./.github/workflows/check-rust.yml
    with:
      rust-version: stable

  check-nightly:
    uses: ./.github/workflows/check-rust.yml
    with:
      rust-version: nightly

  sqlx-check:
    uses: ./.github/workflows/sqlx-check.yml

  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-deny
        run: cargo binstall --no-confirm cargo-deny

      - name: Run cargo deny
        run: cargo deny check bans

  pr-title:
    uses: ./.github/workflows/_pr-title.yml

  release:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    needs: [format, check-stable, check-nightly, sqlx-check, cargo-deny]
    uses: ./.github/workflows/_release.yml
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [check-stable, sqlx-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
